### ISSUE TITLE
Web Config not working anymore

### ISSUE THREAD

**Issue by vzmo777** [frogobox/kick-start-android-webview#18]
Hello Sir,,
the last update of the code source is not working, i think google made an update? i'm not sure.I did everything correctly but the link doesn't work.

Also before this happened when the link was working, if the website used on the app show ads, those ads of the website do not show, and the sound plays in the background, sometimes with a black screen. But admob ads for the app still work.
But now the app is frozen, no link is working. Can you check, thanks.
Error 
![MuMu20230707221858](https://github.com/frogobox/kick-start-android-webview/assets/136829969/6b836485-def5-4454-9714-7f33ba8acfcf)
Screenshot attached.

**Comment by amirisback** [comment]
thank for your report sir, i will fix this bug as soon as possible, thank you 🙏

**Comment by amirisback** [comment]
sir, can u help me? how to reproduce this issue? is happend on what? release? debug? something else?

@vzmo777

**Comment by vzmo777** [comment]
it's on debug mode, i'm not sure if it's also on release cause i didn't
test the release. on Mumu player it's saying the app is not licensed and
does not open.
for the moment the things that i mentioned are the things i detected,
otherwise, is it possible to use chrome engine on it? cause there are a lot
of bugs especially with website ads and it's too slow.
I can share with you a code source I bought from codecanyon that has so
many features, you can merge the code and create something powerful. But to
reskin it it's a bit complicated and takes so much time.
Also the res folder is not well organized. Tell me if you need the code.

Features
  APP FEATURE: 1. Splash Screen (Animation). 2. Permission. 3. AdMob,
AdsManager FAN, UnityAds, Start.io, IronSource (Allow you to earn from your
App). 4. Firebase Analytics. 5. Push notifications. 6. High Performance. 7.
Chrome engine. 8. Download manager, and File upload. 9. Blind view on
screen loader. 10.Loading Bar. 11.Pull-to-Refresh. 12.Deep linking.
13.Responsive Design. 14.Geolocation, intents. 15.Image zoom. 16.Local
pages. 17.Offline Mode & Error handling. 18.No coding skills required. 19.
Clean and well documented code.



Le ven. 7 juil. 2023 à 22:53, Faisal Amir ***@***.***> a
écrit :

**Comment by vzmo777** [comment]
Also, when the external links are open in the app, they remain on the app
and there is no way to return, there is no button.
The ads on the websites as external links must open on an external browser.
and if you can add button back and forward to simplify the navigation.
because the app is stuck in one page, and when we click back button it
exists the app.
I don't know if i'm clear with this, but the navigation is hard without
back button. and external links  and ads on website open in the main screen
on the app, they have to be open externally.

**Comment by vzmo777** [comment]
this is a screenshot when a link is open in a website, its an AD, or
external link.
