### ISSUE TITLE
Renaming the package and app name results in Unresolved reference: R on import com.frogobox.webview.R

### ISSUE THREAD

**Issue by orangpelupa** [frogobox/kick-start-android-webview#7]
if i didnt change the package and app name, it compiles just fine. but once i followed the instruction to change the package and app name, it result 

in Unresolved reference: R on import com.frogobox.webview.R

**Comment by amirisback** [comment]
thank you for making this issue, i will fix and recheck asap

**Comment by orangpelupa** [comment]
Btw may I ask for a feature? Can you add a setting / flag to disable ads?

**Comment by amirisback** [comment]
> Btw may I ask for a feature? Can you add a setting / flag to disable ads?

u can create new issue, so I can put on different board, and different branch

**Comment by amirisback** [comment]
@orangpelupa already done, u can check on master
